[package]
name = "cargo-information"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cargo = "0.73.0"
clap = "4.4.6"
color-print = "0.3.5"


[[bin]]
name = "info"
