[package]
name = "cargo-information"
version = "0.4.1"
edition = "2021"
license = "MIT"
description = "A cargo subcommand to show information about crates."
repository = "https://github.com/hi-rustin/cargo-information"
rust-version = "1.73"

[dependencies]
anstyle = "1.0.4"
anyhow = "1.0.79"
cargo = { version = "0.76.0" }
cargo-credential = { version = "0.4.1" }
cargo-util = "0.2.8"
clap = "4.4.14"
color-print = "0.3.5"
crates-io = "0.39.1"
pathdiff = "0.2.1"
semver = "1.0.21"


[dev-dependencies]
cargo-test-macro = { git = "https://github.com/rust-lang/cargo.git" }
cargo-test-support = { git = "https://github.com/rust-lang/cargo.git" }
snapbox = "0.4.16"
trycmd = "0.14.19"

[[bin]]
name = "cargo-info"

[features]
vendored-openssl = ["cargo/vendored-openssl"]
default = []
