[package]
name = "cargo-information"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A cargo subcommand to show information about crates."
repository = "https://github.com/hi-rustin/cargo-information"
rust-version = "1.73"

[dependencies]
anstyle = "1.0.4"
anyhow = "1.0.75"
cargo = { version = "0.75.1" }
cargo-credential = { version = "0.4.1" }
cargo-util = "0.2.7"
clap = "4.4.11"
color-print = "0.3.5"
crates-io = "0.39.0"


[dev-dependencies]
cargo-test-macro = { git = "https://github.com/rust-lang/cargo.git" }
cargo-test-support = { git = "https://github.com/rust-lang/cargo.git" }
snapbox = "0.4.15"

[[bin]]
name = "cargo-info"
