[package]
name = "cargo-information"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A cargo subcommand to show information about crates."
repository = "https://github.com/hi-rustin/cargo-information"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.4"
anyhow = "1.0.75"
cargo = "0.74.0"
cargo-util = "0.2.6"
clap = "4.4.6"
color-print = "0.3.5"


[[bin]]
name = "info"
